
EXENAME=	clock_test
EXEPATH=	///bin/Classes/

INC=		//include

COMPILER=	SC:c/sc
LINKER=		SC:c/slink

LIBS=		LIB:sc.lib LIB:amiga.lib 

C_OPTS=		opt cpu=68030 INCLUDEDIRECTORY=$(INC) 

C_SOURCES=	clock_test.c

OBJECTS=	clock_test.o

$(EXENAME): $(OBJECTS)
   $(LINKER) WITH <<
 TO $(EXEPATH)$(EXENAME)
 FROM LIB:c.o $(OBJECTS)
 LIBRARY $(LIBS)
<

.c.o:
	$(COMPILER) $(C_OPTS) $*.c

clean:
	@Delete $(OBJECTS)
	@Delete $(EXEPATH)$(EXENAME)
